In [15]:
import pickle
import pandas as pd
import numpy as np

In [19]:
with open('../datos/encodingaccounts.pkl', 'rb') as accounts:
    encoding_accounts = pickle.load(accounts)

with open('../datos/encodingcred_rating.pkl', 'rb') as cred_rating:
    encoding_cred_rating = pickle.load(cred_rating)

with open('../datos/encodingcards.pkl', 'rb') as cards:
    encoding_cards = pickle.load(cards)

with open('../datos/encodinghomes.pkl', 'rb') as homes:
    encoding_homes = pickle.load(homes)

with open('../datos/encodinghousehold.pkl', 'rb') as household:
    encoding_household = pickle.load(household)

with open('../datos/encodingincome_lv.pkl', 'rb') as income_lv:
    encoding_income_lv = pickle.load(income_lv)

with open('../datos/encodingmail_type.pkl', 'rb') as mail_type:
    encoding_mail_type = pickle.load(mail_type)

with open('../datos/encodingowner.pkl', 'rb') as owner:
    encoding_owner = pickle.load(owner)

with open('../datos/encodingprotection.pkl', 'rb') as protection:
    encoding_protection = pickle.load(protection)

with open('../datos/encodingreward.pkl', 'rb') as reward:
    encoding_reward = pickle.load(reward)

with open('../datos/estandarizacion.pkl', 'rb') as estandarizacion:
    estandarizacion = pickle.load(estandarizacion)

with open('../datos/mejor_modelo_gradient.pkl', 'rb') as modelo:
    modelo_gradient = pickle.load(modelo)

with open('../datos/knn2.pkl', 'rb') as modelo2:
    modelo_knn2 = pickle.load(modelo2)

In [20]:
reward_orden = ["Cash Back", "Points", "Air Miles"]
mail_orden = ["Letter", "Postcard"]
income_orden = ["High", "Low", "Medium"]
accounts_orden = ["3", "2", "1"]
protection_orden = ["No", "Yes"]
cred_order = ['High', 'Medium', 'Low']
cards_order = ["4", "3", "1", "2"]
homes_order = ["3", "2", "1"]
household_order = ["bajo", "medio", "alto"]
owner_order = ['No', 'Yes']
dic_household = {"1" : "bajo", "2": "medio", "3": "alto", "4": "alto", "5" : "medio",
                "6": "bajo", "7": "bajo", "8": "bajo", "9": "bajo"}

In [21]:
dic_household = {"1" : "bajo", "2": "medio", "3": "alto", "4": "alto", "5" : "medio",
                "6": "bajo", "7": "bajo", "8": "bajo", "9": "bajo"}
resultados = {
"reward" : str(input("¿Qué tipo de programa de recompensa tiene? ¿'Cash Back', 'Points' or 'Air Miles'?")),
"mail_type" : str(input("¿'Letter' or 'Postcard'?")),
"income_lv" : str(input("¿Nivel de ingresos?¿'High', 'Low' or 'Medium'?")),
"accounts" : str(input("¿ cuántas cuentas no de tarjeta de crédito tiene el cliente? Entre 1 y 3.")),
"protection" : str(input("¿Tiene protección?¿'Yes' or 'No'?")),
"cred_rating" : str(input("¿Nivel de credit rating?¿'Low', 'Medium' or 'High'?")),
"cards" : str(input("¿Número de tarjetas de crédito poseídas en el banco? Entre 1 y 4.")),
"homes" : str(input("¿Número de viviendas poseídas por el cliente? Entre 1 y 3." )),
"household" : dic_household[str(input("¿Número de individuos en la familia? Entre 1 y 9."))],
"owner" : str(input("¿El cliente es propietario de su hogar?¿'Yes' or 'No' ?")),
"balanceQ1" : float(input("¿BalanceQ1?")),
"balanceQ2" : float(input("¿BalanceQ2?")),
"balanceQ3" : float(input("¿BalanceQ3?")),
"balanceQ4" : float(input("¿BalanceQ4?")),
"balance" : float(input("¿Balance?"))}

In [22]:
df_resultados = pd.DataFrame(resultados, index=[0])
df_resultados

reward mail_type income_lv accounts protection cred_rating cards homes  \
0  Points    Letter      High        2         No      Medium     2     2   

  household owner  balanceQ1  balanceQ2  balanceQ3  balanceQ4  balance  
0      alto   Yes     1350.0     1350.0     1350.0     1350.0   1350.0

In [23]:
columnas_numeric = df_resultados.select_dtypes(include = np.number).columns
columnas_numeric


Index(['balanceQ1', 'balanceQ2', 'balanceQ3', 'balanceQ4', 'balance'], dtype='object')

In [24]:
estandarizadas = pd.DataFrame(estandarizacion.transform(df_resultados[columnas_numeric]), columns = columnas_numeric)
estandarizadas

balanceQ1  balanceQ2  balanceQ3  balanceQ4   balance
0   0.942064   0.511979   0.471023   0.487923  0.762467

In [25]:
reward = pd.DataFrame(encoding_reward.transform(df_resultados[["reward"]]), columns = ["reward"])
mail_type = pd.DataFrame(encoding_mail_type.transform(df_resultados[["mail_type"]]), columns = ["mail_type"])
income_lv = pd.DataFrame(encoding_income_lv.transform(df_resultados[["income_lv"]]), columns = ["income_lv"])
accounts = pd.DataFrame(encoding_accounts.transform(df_resultados[["accounts"]]), columns = ["accounts"])
protection = pd.DataFrame(encoding_protection.transform(df_resultados[["protection"]]), columns = ["protection"])
cred_rating = pd.DataFrame(encoding_cred_rating.transform(df_resultados[["cred_rating"]]), columns = ["cred_rating"])
cards = pd.DataFrame(encoding_cards.transform(df_resultados[["cards"]]), columns = ["cards"])
homes = pd.DataFrame(encoding_homes.transform(df_resultados[["homes"]]), columns = ["homes"])
household = pd.DataFrame(encoding_household.transform(df_resultados[["household"]]), columns = ["household"])
owner = pd.DataFrame(encoding_owner.transform(df_resultados[["owner"]]), columns = ["owner"])

In [26]:
df_final = pd.concat([reward, mail_type, income_lv, accounts, protection, cred_rating, cards, homes, household, owner, estandarizadas], axis = 1)
df_final

reward  mail_type  income_lv  accounts  protection  cred_rating  cards  \
0       1          0          0         1           0            1      3   

   homes  household  owner  balanceQ1  balanceQ2  balanceQ3  balanceQ4  \
0      1          2      1   0.942064   0.511979   0.471023   0.487923   

    balance  
0  0.762467

In [30]:
modelo_gradient.predict(df_final)


array([0])

In [31]:
modelo_gradient.predict_proba(df_final)

array([[0.65198046, 0.34801954]])

In [29]:
modelo_knn2.predict(df_final)

array([1])

In [32]:
modelo_knn2.predict_proba(df_final)

array([[0., 1.]])